//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleClientForWSA.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/aFromCelsiustoFahrenheit", ReplyAction="*")]
        int aFromCelsiustoFahrenheit(int Celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/aFromCelsiustoFahrenheit", ReplyAction="*")]
        System.Threading.Tasks.Task<int> aFromCelsiustoFahrenheitAsync(int Celsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/aFromFahrenheittoCelsius", ReplyAction="*")]
        int aFromFahrenheittoCelsius(int Fahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/aFromFahrenheittoCelsius", ReplyAction="*")]
        System.Threading.Tasks.Task<int> aFromFahrenheittoCelsiusAsync(int Fahrenheit);
        
        // CODEGEN: Generating message contract since element name bDateTimeDisplayResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/bDateTimeDisplay", ReplyAction="*")]
        ConsoleClientForWSA.ServiceReference1.bDateTimeDisplayResponse bDateTimeDisplay(ConsoleClientForWSA.ServiceReference1.bDateTimeDisplayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/bDateTimeDisplay", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleClientForWSA.ServiceReference1.bDateTimeDisplayResponse> bDateTimeDisplayAsync(ConsoleClientForWSA.ServiceReference1.bDateTimeDisplayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/dEuroToLei", ReplyAction="*")]
        double dEuroToLei(double Lei);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/dEuroToLei", ReplyAction="*")]
        System.Threading.Tasks.Task<double> dEuroToLeiAsync(double Lei);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/dLeiToEuro", ReplyAction="*")]
        double dLeiToEuro(double Euro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/dLeiToEuro", ReplyAction="*")]
        System.Threading.Tasks.Task<double> dLeiToEuroAsync(double Euro);
        
        // CODEGEN: Generating message contract since element name cfiveElementsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cfiveElements", ReplyAction="*")]
        ConsoleClientForWSA.ServiceReference1.cfiveElementsResponse cfiveElements(ConsoleClientForWSA.ServiceReference1.cfiveElementsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cfiveElements", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleClientForWSA.ServiceReference1.cfiveElementsResponse> cfiveElementsAsync(ConsoleClientForWSA.ServiceReference1.cfiveElementsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bDateTimeDisplayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bDateTimeDisplay", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleClientForWSA.ServiceReference1.bDateTimeDisplayRequestBody Body;
        
        public bDateTimeDisplayRequest() {
        }
        
        public bDateTimeDisplayRequest(ConsoleClientForWSA.ServiceReference1.bDateTimeDisplayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class bDateTimeDisplayRequestBody {
        
        public bDateTimeDisplayRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bDateTimeDisplayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bDateTimeDisplayResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleClientForWSA.ServiceReference1.bDateTimeDisplayResponseBody Body;
        
        public bDateTimeDisplayResponse() {
        }
        
        public bDateTimeDisplayResponse(ConsoleClientForWSA.ServiceReference1.bDateTimeDisplayResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class bDateTimeDisplayResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string bDateTimeDisplayResult;
        
        public bDateTimeDisplayResponseBody() {
        }
        
        public bDateTimeDisplayResponseBody(string bDateTimeDisplayResult) {
            this.bDateTimeDisplayResult = bDateTimeDisplayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cfiveElementsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cfiveElements", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleClientForWSA.ServiceReference1.cfiveElementsRequestBody Body;
        
        public cfiveElementsRequest() {
        }
        
        public cfiveElementsRequest(ConsoleClientForWSA.ServiceReference1.cfiveElementsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class cfiveElementsRequestBody {
        
        public cfiveElementsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cfiveElementsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cfiveElementsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleClientForWSA.ServiceReference1.cfiveElementsResponseBody Body;
        
        public cfiveElementsResponse() {
        }
        
        public cfiveElementsResponse(ConsoleClientForWSA.ServiceReference1.cfiveElementsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class cfiveElementsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleClientForWSA.ServiceReference1.ArrayOfString cfiveElementsResult;
        
        public cfiveElementsResponseBody() {
        }
        
        public cfiveElementsResponseBody(ConsoleClientForWSA.ServiceReference1.ArrayOfString cfiveElementsResult) {
            this.cfiveElementsResult = cfiveElementsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ConsoleClientForWSA.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ConsoleClientForWSA.ServiceReference1.WebService1Soap>, ConsoleClientForWSA.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int aFromCelsiustoFahrenheit(int Celsius) {
            return base.Channel.aFromCelsiustoFahrenheit(Celsius);
        }
        
        public System.Threading.Tasks.Task<int> aFromCelsiustoFahrenheitAsync(int Celsius) {
            return base.Channel.aFromCelsiustoFahrenheitAsync(Celsius);
        }
        
        public int aFromFahrenheittoCelsius(int Fahrenheit) {
            return base.Channel.aFromFahrenheittoCelsius(Fahrenheit);
        }
        
        public System.Threading.Tasks.Task<int> aFromFahrenheittoCelsiusAsync(int Fahrenheit) {
            return base.Channel.aFromFahrenheittoCelsiusAsync(Fahrenheit);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleClientForWSA.ServiceReference1.bDateTimeDisplayResponse ConsoleClientForWSA.ServiceReference1.WebService1Soap.bDateTimeDisplay(ConsoleClientForWSA.ServiceReference1.bDateTimeDisplayRequest request) {
            return base.Channel.bDateTimeDisplay(request);
        }
        
        public string bDateTimeDisplay() {
            ConsoleClientForWSA.ServiceReference1.bDateTimeDisplayRequest inValue = new ConsoleClientForWSA.ServiceReference1.bDateTimeDisplayRequest();
            inValue.Body = new ConsoleClientForWSA.ServiceReference1.bDateTimeDisplayRequestBody();
            ConsoleClientForWSA.ServiceReference1.bDateTimeDisplayResponse retVal = ((ConsoleClientForWSA.ServiceReference1.WebService1Soap)(this)).bDateTimeDisplay(inValue);
            return retVal.Body.bDateTimeDisplayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleClientForWSA.ServiceReference1.bDateTimeDisplayResponse> ConsoleClientForWSA.ServiceReference1.WebService1Soap.bDateTimeDisplayAsync(ConsoleClientForWSA.ServiceReference1.bDateTimeDisplayRequest request) {
            return base.Channel.bDateTimeDisplayAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleClientForWSA.ServiceReference1.bDateTimeDisplayResponse> bDateTimeDisplayAsync() {
            ConsoleClientForWSA.ServiceReference1.bDateTimeDisplayRequest inValue = new ConsoleClientForWSA.ServiceReference1.bDateTimeDisplayRequest();
            inValue.Body = new ConsoleClientForWSA.ServiceReference1.bDateTimeDisplayRequestBody();
            return ((ConsoleClientForWSA.ServiceReference1.WebService1Soap)(this)).bDateTimeDisplayAsync(inValue);
        }
        
        public double dEuroToLei(double Lei) {
            return base.Channel.dEuroToLei(Lei);
        }
        
        public System.Threading.Tasks.Task<double> dEuroToLeiAsync(double Lei) {
            return base.Channel.dEuroToLeiAsync(Lei);
        }
        
        public double dLeiToEuro(double Euro) {
            return base.Channel.dLeiToEuro(Euro);
        }
        
        public System.Threading.Tasks.Task<double> dLeiToEuroAsync(double Euro) {
            return base.Channel.dLeiToEuroAsync(Euro);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleClientForWSA.ServiceReference1.cfiveElementsResponse ConsoleClientForWSA.ServiceReference1.WebService1Soap.cfiveElements(ConsoleClientForWSA.ServiceReference1.cfiveElementsRequest request) {
            return base.Channel.cfiveElements(request);
        }
        
        public ConsoleClientForWSA.ServiceReference1.ArrayOfString cfiveElements() {
            ConsoleClientForWSA.ServiceReference1.cfiveElementsRequest inValue = new ConsoleClientForWSA.ServiceReference1.cfiveElementsRequest();
            inValue.Body = new ConsoleClientForWSA.ServiceReference1.cfiveElementsRequestBody();
            ConsoleClientForWSA.ServiceReference1.cfiveElementsResponse retVal = ((ConsoleClientForWSA.ServiceReference1.WebService1Soap)(this)).cfiveElements(inValue);
            return retVal.Body.cfiveElementsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleClientForWSA.ServiceReference1.cfiveElementsResponse> ConsoleClientForWSA.ServiceReference1.WebService1Soap.cfiveElementsAsync(ConsoleClientForWSA.ServiceReference1.cfiveElementsRequest request) {
            return base.Channel.cfiveElementsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleClientForWSA.ServiceReference1.cfiveElementsResponse> cfiveElementsAsync() {
            ConsoleClientForWSA.ServiceReference1.cfiveElementsRequest inValue = new ConsoleClientForWSA.ServiceReference1.cfiveElementsRequest();
            inValue.Body = new ConsoleClientForWSA.ServiceReference1.cfiveElementsRequestBody();
            return ((ConsoleClientForWSA.ServiceReference1.WebService1Soap)(this)).cfiveElementsAsync(inValue);
        }
    }
}
